### ISSUE TITLE
[Todo] Features that require documentation

### ISSUE THREAD

**Issue by mirkobrombin** [unified-ban/Docs#4]
## Getting Started
- [x] Welcome
- [x] First setup
- [x] Enable dashboard
- [x] Privacy

## Features
- [x] Alias
- [x] Announce
- [ ] Antiflood
- [ ] Antispam
- [ ] Antiscam
- [x] Invite
- [x] Non-Latin filter
- [x] RTL Name filter
- [ ] Language
- [x] Bad Words
- [x] Safe groups
- [x] Blacklist
- [ ] Translations
- [x] Welcome + Welcome Buttons
- [x] Ban
- [x] Support (Call + Start Support + End Support)
- [x] Captcha (this should refer to Welcome documentation)
- [x] Check
- [ ] Config (this should be referenced from First setup documentation)
- [x] Enable + Disable
- [x] Echo
- [x] Feedback (this should be referenced from Contribute/Feedback documentation)
- [x] Gate
- [x] Get
- [ ] Trust Factor
- [x] Help
- [x] Id
- [x] Kick
- [x] Leave
- [x] Motd
- [x] Mute
- [x] Pin
- [ ] Reloads
- [ ] Report
- [x] Delete (rm)
- [x] Rules + Set Rules
- [x] Start
- [x] Status
- [x] Test

## Contribute
- [x] Bug report
- [ ] Feature request
- [ ] Translate
